{
 "title": "iLO",
 "description": "iLO data from https://github.com/MauveSoftware/ilo_exporter",
 "tags": [
  "ilo",
  "ipmi"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "HOST:",
    "query": {
     "query": "label_values(ilo_manager_info,host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Power Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "ilo_power_up{host='$node'}", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ilo_power_current_watt{host='$node'}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Power usage 30d",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ilo_power_current_watt{host='$node'} * 30 * 24 "
    }
   ]
  },
  {
   "title": "Unhealthy DIMMs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ilo_memory_dimm_healthy{host='$node'}) - count(ilo_memory_dimm_healthy{host='$node'} == 1)"
    }
   ]
  },
  {
   "title": "Disabled PSUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ilo_power_supply_enabled{host='$node'}) - count(ilo_power_supply_enabled{host='$node'} == 1)"
    }
   ]
  },
  {
   "title": "Unhealthy PSUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ilo_power_supply_healthy{host='$node'}) - count(ilo_power_supply_healthy{host='$node'} == 1)"
    }
   ]
  },
  {
   "title": "Unhealthy Processors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ilo_processor_healthy{host='$node'}) - count(ilo_processor_healthy{host='$node'} == 1)"
    }
   ]
  },
  {
   "title": "Unhealthy Disks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ilo_storage_disk_healthy{host='$node'}) - count(ilo_storage_disk_healthy{host='$node'} == 1)"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ilo_chassis_temperature_current{host='$node'}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ilo_chassis_temperature_current{host='$node'}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fans Speed (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ilo_chassis_fan_current_percent{host='$node'}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power (W)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ilo_power_current_watt{host='$node'}",
     "legendFormat": "Current"
    },
    {
     "expr": "ilo_power_average_watt{host='$node'}",
     "legendFormat": "Average"
    },
    {
     "expr": "ilo_power_min_watt{host='$node'}",
     "legendFormat": "Min"
    },
    {
     "expr": "ilo_power_max_watt{host='$node'}",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 } }
 ]
}